spring:
  profiles.active: default
server:
  port: 8090
---
spring:
  profiles: default
  #jmx.enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: Common@123
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
security:
  basic:
    enabled: false

logging.level.org.hibernate.SQL: debug
  